version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Cake.Core
    update-types: ["version-update:semver-minor"]
  - dependency-name: Cake.Testing
    update-types: ["version-update:semver-minor"]
  - dependency-name: Cake.AzureDevOps
    update-types: ["version-update:semver-minor"]
  - dependency-name: Cake.Issues
    update-types: ["version-update:semver-minor"]
  - dependency-name: Cake.Issues.Testing
    update-types: ["version-update:semver-minor"]
  - dependency-name: Cake.Issues.PullRequests
    update-types: ["version-update:semver-minor"]